const images = {
  critter: { thumb: 'critter.jpeg', full: 'critter_full.png' },
  art: { thumb: 'art.jpeg', full: 'art_full.png' },
  dan_and_flo: { thumb: 'dan_and_flo.jpeg', full: 'dan_and_flo_full.jpeg' },
  hike: { thumb: 'hike.jpeg', full: 'hike_full.png' },
  wuerstchen: { thumb: 'wuerstchen.jpeg', full: 'wuerstchen_full.png' },
  madison: { thumb: 'madison.jpeg', full: 'madison_full.png' },
  grand_canyon_bruecke: { thumb: 'grand_canyon_bruecke.jpeg', full: 'grand_canyon_bruecke_full.png' },
  scared_of_heights: { thumb: 'scared_of_heights.JPG', full: 'scared_of_heights_full.JPG' },
  green_river: { thumb: 'green_river.jpeg', full: 'green_river_full.jpeg' },
  foo: { thumb: 'foo.jpeg', full: 'foo_full.png' },
  sleepy_seb: { thumb: 'sleepy_seb.jpeg', full: 'sleepy_seb_full.png' },
  tuer: { thumb: 'tuer.jpeg', full: 'tuer_full.png' },
  you_look_great: { thumb: 'you_look_great.jpeg', full: 'you_look_great_full.png' },
  alpen: { thumb: 'alpen.jpeg', full: 'alpen_full.png' },
  sparty: { thumb: 'sparty.JPG', full: 'sparty_full.JPG' },
  muddy_car: { thumb: 'muddy_car.jpeg', full: 'muddy_car_full.png' },
  canyon: { thumb: 'canyon.jpeg', full: 'canyon_full.jpeg' },
  chrizz: { thumb: 'chrizz.jpeg', full: 'chrizz_full.jpeg' },
  yum: { thumb: 'yum.jpeg', full: 'yum_full.png' },
  park: { thumb: 'park.jpeg', full: 'park_full.png' },
  cocomero: { thumb: 'cocomero.png', full: 'cocomero_full.PNG' },
  forgot_where_this_is: { thumb: 'forgot_where_this_is.jpeg', full: 'forgot_where_this_is_full.png' },
  patricks_day_street: { thumb: 'patricks_day_street.jpeg', full: 'patricks_day_street_full.jpeg' },
  lake_powell: { thumb: 'lake_powell.jpeg', full: 'lake_powell_full.png' },
  dan_seb_budapest: { thumb: 'dan_seb_budapest.jpg', full: 'dan_seb_budapest_full.jpg' },
  letzter_tag_in_budapest: { thumb: 'letzter_tag_in_budapest.jpg', full: 'letzter_tag_in_budapest_full.jpg' },
  dan_mo_budapest: { thumb: 'dan_mo_budapest.JPG', full: 'dan_mo_budapest_full.JPG' },
  katze: { thumb: 'katze.jpeg', full: 'katze_full.jpeg' },
  memphis: { thumb: 'memphis.jpeg', full: 'memphis_full.jpeg' },
  grand_canyon_ueberblick: { thumb: 'grand_canyon_ueberblick.jpeg', full: 'grand_canyon_ueberblick_full.png' },
  patricks_day_platform: { thumb: 'patricks_day_platform.jpeg', full: 'patricks_day_platform_full.jpeg' },
  orleans_hotel: { thumb: 'orleans_hotel.jpeg', full: 'orleans_hotel_full.jpeg' },
  cool_view: { thumb: 'cool_view.jpeg', full: 'cool_view_full.png' },
  grad: { thumb: 'grad.jpeg', full: 'grad_full.jpeg' },
  seb_in_the_river: { thumb: 'seb_in_the_river.jpeg', full: 'seb_in_the_river_full.png' },
  chicago: { thumb: 'chicago.jpeg', full: 'chicago_full.jpeg' },
};

export default images;
